name: "A simple test action"
description: "Tests the thing"
inputs:
  executable:
    description: "Executable file"
    required: true
  icon-file:
    description: "Icon file to use for Executable"
    required: true
  desktop-file:
    description: "Desktop file to use for Executable"
    required: true

runs:
  using: "composite"

  steps:
    - name: Print the name
      run: |
        echo "Hello ${{ inputs.executable }}!"
      shell: bash

    - name: Print docker env var
      run: |
        echo "Hello $GTK4!"
      shell: bash
