on:
  push:
  pull_request:
  workflow_dispatch:

name: CI

env:
  GTK_VERSION: 4.14.4

jobs:
  build-linux-appimage:
    permissions:
      contents: read

    # TODO needs: create-docker-image

    name: Build Linux AppImage
    runs-on: ubuntu-latest

    container:
      # TODO image: ghcr.io/${{ github.repository }}-gtk:${{ needs.create-docker-image.outputs.TAG }} # TODO ${{ env.IMAGE_NAME }}:${{ env.TAG }}
      image: ghcr.io/${{ github.repository }}-gtk:4.14.4
      options: --user root # see: https://github.com/actions/checkout/issues/1014
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Install toolchain
        run: |
          export HOME="/home/runner"
          echo $PATH
          echo $HOME
          echo $USER
          rustup toolchain install stable
          rustup default stable

      - name: Build packetry binary
        run: cargo build --release

      - name: Test under XVFB (Linux)
        run: xvfb-run cargo test
        if: runner.os == 'Linux'

      - name: Run build-appimage action (Linux)
        uses: ./appimage/actions/build-appimage/
        with:
          executable:   ./target/release/packetry
          icon-file:    ./appimage/dist/icon.png
          desktop-file: ./appimage/dist/packetry.desktop

      - name: Upload AppImage binary (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: Linux AppImage binary
          path: |
            packetry-x86_64.AppImage
          if-no-files-found: error


  create-docker-image:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    name: Create Docker image
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ env.GTK_VERSION }} # see: https://github.com/actions/runner/issues/1189

    steps:
      - name: Check variables
        run: |
          echo     OWNER IS: ${{ github.repository_owner }}
          echo     REPO  IS: ${{ github.repository }}
          echo  REGISTRY IS:  ${{ env.REGISTRY }}
          echo     ACTOR IS:  ${{ github.actor }}
          echo    SECRET IS:  ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          echo     IMAGE IS:  ${{ env.IMAGE_NAME }}
          echo  REF_NAME IS:  ${{ github.ref_name }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: appimage/actions/build-appimage/docker/
          push: true
          tags: ghcr.io/${{ github.repository }}-gtk:${{ env.GTK_VERSION }} # TODO ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          cache-from: type=gha, scope=${{ github.ref_name }}
          cache-to:   type=gha,  scope=${{ github.ref_name }}, mode=max

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}-gtk # TODO ${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
