on:
  push:
  pull_request:
  workflow_dispatch:

name: CI

jobs:

  test_local:
    name: Build and test (AppImage)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List Dir
        run: |
          ls -al .github/workflows/

      # - name: Print name
      #   uses: ./appimage/actions/test-action/
      #   with:
      #     NAME: ${{ inputs.NAME }}

      - name: Build Packetry AppImage
        uses: ./appimage/actions/build-appimage/
        with:
          executable:   ./target/release/packetry
          icon-file:    ./appimage/dist/icon.png
          desktop-file: ./appimage/dist/packetry.desktop
