on:
  push:
  pull_request:
  workflow_dispatch:

name: CI-remote

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-docker-image:
    name: Build the gtk:test docker image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: appimage/actions/build-appimage/docker/
          push: false
          tags: "test" # ${{ steps.meta.outputs.tags }}
          #labels: ${{ steps.meta.outputs.labels }}

  test-remote:
    needs: build-and-push-docker-image

    name: Build and test (AppImage)
    runs-on: ubuntu-latest

    container:
      image: gtk:test
      volumes:
        - /tmp/act:/tmp/act

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Action
        uses: ./appimage/actions/test-action/
        with:
          executable:   ./target/release/packetry
