on:
  push:
  pull_request:
  workflow_dispatch:

name: CI-remote

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-docker-image:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    name: Build the gtk:test docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: appimage/actions/test-action/docker/
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/gtk:remote
          cache-from: type=gha, scope=${{ github.ref_name }}
          cache-to:   type=gha, scope=${{ github.ref_name }}

  test-remote:
    permissions:
      contents: read

    needs: build-and-push-docker-image

    name: Build and test (AppImage)
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository_owner }}/gtk:remote
      options: --user root # see: https://github.com/actions/checkout/issues/1014
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
      volumes:
        - /tmp/act:/tmp/act

    steps:
      # - name: fix permissions error on actions/checkout@v4
      #   # see this bug: https://github.com/actions/checkout/issues/1014
      #   run: chmod +w -R ${GITHUB_WORKSPACE}; rm -rf ${GITHUB_WORKSPACE}/*;

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Action
        uses: ./appimage/actions/test-action/
        with:
          executable:   ./target/release/packetry
