on:
  push:
  pull_request:
  workflow_dispatch:

name: CI-remote

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-docker-image:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    name: Build the gtk:test docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          #context: appimage/actions/test-action/docker/
          context: appimage/actions/build-appimage/docker/
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/gtk:remote
          cache-from: type=gha, scope=${{ github.ref_name }}
          cache-to:   type=gha,  scope=${{ github.ref_name }}, mode=max

  test-remote:
    permissions:
      contents: read

    needs: build-and-push-docker-image

    name: Build and test (AppImage)
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository_owner }}/gtk:remote
      options: --user root # see: https://github.com/actions/checkout/issues/1014
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
      volumes:
        - /tmp/act:/tmp/act

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Action
        uses: ./appimage/actions/test-action/
        with:
          executable: ./target/release/packetry
