on:
  push:
  pull_request:
  workflow_dispatch:

name: CI

defaults:
  run:
    shell: bash
    working-directory: /home/runner

jobs:
  test-remote:
    permissions:
      contents: read

    needs: test-remote-create-docker-image

    name: Build and test
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ needs.create-docker-image.outputs.NAME }}:${{ needs.create-docker-image.outputs.TAG }}
      options: --user root # see: https://github.com/actions/checkout/issues/1014
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check environment
        run: |
          echo PATH: $PATH
          echo HOME: $HOME
          echo pwd:  `pwd`
          ls -al

      - name: Test Action
        uses: ./appimage/test/
        with:
          executable: ./target/release/packetry


  test-remote-create-docker-image:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    name: Create Docker image
    runs-on: ubuntu-latest
    outputs:
      NAME: ${{ github.repository }}-test-${{ env.GTK_VERSION }}
      TAG:  ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changed
        with:
          filters: |
            dockerfile:
              - "appimage/test/docker/**"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: appimage/test/docker/
          push: true
          tags: ghcr.io/${{ github.repository }}-test-${{ env.GTK_VERSION }}:${{ github.ref_name }}
          cache-from: type=gha, scope=${{ github.ref_name }}
          cache-to:   type=gha,  scope=${{ github.ref_name }}, mode=max

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}-test
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
